version: '2'
services:
  mysql:
    image: mysql:latest
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ec95c258266b8e985848cae688effa2b
  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: ec95c258266b8e985848cae688effa2b
volumes:
  mysql:
